- .github/workflows/build.yml
Removes PHP7.2 from github actions build.
> Remove PHP 7.2 from build

- .github/ISSUE_TEMPLATE/bug_report.md
- plugins/exception-render/src/EntityValidationListener.php
- plugins/exception-render/src/MixerApiExceptionRenderer.php
- plugins/exception-render/src/ValidationException.php
Resolves #23 
Also adds bug_report.md
> [MixerApi\ExceptionRender] - ValidationException not working in docblock

- plugins/rest/src/Lib/AutoRouter.php
- plugins/rest/src/Lib/Controller/ReflectedControllerDecorator.php
> MixerApi\Rest] - Only auto route methods which exist in the controller

- docs/index.md
adds instructions for mixerapi/app
> skeleton install instructions

- plugins/exception-render/src/MixerApiExceptionRenderer.php
> Add stack trace to exception responses (if debug on)

- plugins/exception-render/src/MixerApiExceptionRenderer.php
- plugins/exception-render/src/ValidationException.php
- plugins/exception-render/tests/TestCase/ControllerTest.php
Also refactors code for cleanliness.
Resolves #32
> Now sets the correct status code #32

- plugins/bake/templates/bake/element/Controller/add.twig
- plugins/bake/templates/bake/element/Controller/delete.twig
- plugins/bake/templates/bake/element/Controller/edit.twig
- plugins/bake/templates/bake/element/Controller/index.twig
- plugins/bake/templates/bake/element/Controller/view.twig
- plugins/bake/tests/assets/DepartmentsController.php
> Corrects MethodNotAllowedException namespace

- grumphp.yml
- plugins/mixerapi/.gitignore
- plugins/mixerapi/assets/Application.php
- plugins/mixerapi/assets/Welcome.php
- plugins/mixerapi/assets/WelcomeController.php
- plugins/mixerapi/assets/app.php
- plugins/mixerapi/assets/routes.php
- plugins/mixerapi/assets/swagger.yml
- plugins/mixerapi/assets/swagger_bake.php
- plugins/mixerapi/composer.json
- plugins/mixerapi/src/Console/Installer.php
- plugins/mixerapi/tests/TestCase/Console/InstallerTest.php
- plugins/mixerapi/tests/TestCase/Console/Io.php
Adds an interactive composer post-install task to act as an application skeleton.
> [MixerApi] - Adds post installer

- .github/workflows/build.yml
- plugins/bake/templates/bake/element/Controller/add.twig
- plugins/bake/templates/bake/element/Controller/edit.twig
> [Bake] - Add ValidationException in output for add() and edit()

- plugins/mixerapi/composer.json
Issue: #47
Set composer > type to cakephp-plugin
None
> [MixerApi] Set composer > type to cakephp-plugin

- plugins/mixerapi/src/Command/InstallCommand.php
Issue: #50
Fixes help text.
n/a
> [MixerApi] Fixes option help text

- plugins/mixerapi/src/Welcome.php
- plugins/mixerapi/tests/TestCase/PluginTest.php
- plugins/mixerapi/tests/TestCase/WelcomeTest.php
Issue: 46#
- Lightly refactors Welcome to make it easier to test
- Use snake_case for PluginTest methods
n/a
> [MixerApi] Adds unit tests for Welcome

- composer.json
- composer.lock
Issue: #20
Upgrades PHPMD for PHP 8 compatability.
n/a
> Upgrade PHPMD #20

- docs/install.md
- plugins/core/src/Response/ResponseModifier.php
- plugins/core/tests/TestCase/Response/ResponseModifierTest.php
Improves test coverage and comments for the ResponseModifier
n/a
> [Core] - Response modifier code coverage

- docs/install.md
- plugins/rest/src/Command/ListRoutesCommand.php
- plugins/rest/tests/TestCase/Command/ListRoutesCommandTest.php
improve code coverage and fix broken unit tests
n/a
> [Rest] - List routes command test coverage

- docs/install.md
- plugins/collection-view/src/View/JsonCollectionView.php
- plugins/collection-view/src/View/XmlCollectionView.php
- plugins/collection-view/tests/TestCase/ConfigurationTest.php
- plugins/collection-view/tests/TestCase/ControllerTest.php
- plugins/collection-view/tests/TestCase/SerializerTest.php
- plugins/collection-view/tests/TestCase/View/ControllerFactory.php
- plugins/collection-view/tests/TestCase/View/JsonCollectionViewTest.php
- plugins/collection-view/tests/TestCase/View/XmlCollectionViewTest.php
> Collection view test coverage

- docs/install.md
- plugins/core/src/Model/ModelPropertyFactory.php
- plugins/core/src/Model/TableScanner.php
- plugins/core/tests/TestCase/Model/ModelTest.php
- plugins/core/tests/TestCase/Model/TableScannerTest.php
- plugins/exception-render/src/EntityValidationListener.php
- plugins/hal-view/tests/TestCase/View/HalJsonViewTest.php
- plugins/json-ld-view/tests/TestCase/View/JsonLdViewTest.php
- plugins/rest/src/Lib/Parser/RouteScopeFinder.php
- plugins/rest/tests/TestCase/Lib/Controller/ReflectedControllerDecoratorTest.php
> Test coverage

- docs/install.md
- plugins/collection-view/README.md
- plugins/exception-render/README.md
- plugins/hal-view/README.md
- plugins/json-ld-view/README.md
- plugins/mixerapi/README.md
- plugins/rest/README.md
Removes alpha stage messaging from readme.md files
> Remove alpha messaging

- plugins/bake/composer.json
- plugins/collection-view/composer.json
- plugins/core/composer.json
- plugins/exception-render/composer.json
- plugins/hal-view/composer.json
- plugins/mixerapi/composer.json
- plugins/rest/composer.json
Removes require-dev and scripts from plugins. These are not required.
> Updates composer

- plugins/json-ld-view/src/Controller/Component/JsonLdContextComponent.php
- plugins/json-ld-view/tests/TestCase/Controller/JsonLdControllerTest.php
- plugins/json-ld-view/tests/TestCase/JsonLdSchemaTest.php
- plugins/json-ld-view/tests/TestCase/JsonSerializerTest.php
- plugins/json-ld-view/tests/TestCase/SchemaMapperTest.php
Issue: #64
Resolves bug
See issue.
> [JsonLdView] - Class not found run time exception

- plugins/mixerapi/composer.json
- plugins/mixerapi/src/Plugin.php
Load MixerApi/Bake as dev dependency only
> [MixerApi] - make mixerapi/bake optional

- .github/workflows/build.yml
- plugins/bake/src/Plugin.php
- plugins/collection-view/src/Plugin.php
- plugins/exception-render/src/Plugin.php
- plugins/hal-view/src/Plugin.php
- plugins/json-ld-view/src/Plugin.php
- plugins/mixerapi/src/Plugin.php
- plugins/rest/src/Plugin.php
> Disable unused middleware, services, and routes

- plugins/crud/README.md
- plugins/crud/src/Interfaces/DeleteInterface.php
- plugins/crud/src/Interfaces/ReadInterface.php
- plugins/crud/src/Interfaces/UpdateInterface.php
- plugins/crud/src/Services/CrudTrait.php
- plugins/crud/src/Services/Delete.php
- plugins/crud/src/Services/Read.php
- plugins/crud/src/Services/Update.php
- plugins/mixerapi/composer.json
- plugins/mixerapi/src/Plugin.php
> [MixerApi/Crud] Add getQuery to Read

- plugins/core/src/Model/Model.php
- plugins/core/src/Model/ModelProperty.php
- plugins/core/src/Model/ModelPropertyFactory.php
- plugins/core/tests/TestCase/Model/ModelTest.php
- plugins/core/tests/test_app/src/Model/Entity/Actor.php
- plugins/jwt-auth/README.md
- plugins/mixerapi/composer.json
Adds isHidden and isAccessible to ModelProperty using Entity `$_hidden` and `$_accessible`.
> [MixerApi/Core] - Adds support for Entity accessible and  hidden to ModelProperty

- .github/workflows/pull-request.yml
- .gitignore
- composer.lock
- config/bootstrap.php
- plugins/exception-render/README.md
- plugins/exception-render/src/EntityValidationListener.php
- plugins/exception-render/tests/TestCase/EntityValidationTest.php
- plugins/jwt-auth/tests/ControllerTest.php
- plugins/jwt-auth/tests/test_app/src/Controller/TestController.php
> [ValidationException] - Add config option to turn off ValidationException

- plugins/exception-render/src/ValidationException.php
- plugins/exception-render/tests/TestCase/EntityValidationTest.php
- plugins/exception-render/tests/TestCase/ValidationExceptionTest.php
> [ExceptionRender] - Adds ValidationException::getEntity()

- plugins/crud/README.md
- plugins/crud/src/Interfaces/CreateInterface.php
- plugins/crud/src/Interfaces/DeleteInterface.php
- plugins/crud/src/Interfaces/ReadInterface.php
- plugins/crud/src/Interfaces/UpdateInterface.php
- plugins/crud/src/Services/Create.php
- plugins/crud/src/Services/Delete.php
- plugins/crud/src/Services/Read.php
- plugins/crud/src/Services/Update.php
> [Crud] Adds ability to pass table options through CRUD

- plugins/hal-view/src/JsonSerializer.php
- plugins/json-ld-view/src/JsonSerializer.php
> [JsonLdView] [HalJsonView] - Use ResultSetInterface instead of ResultSet concrete

- plugins/jwt-auth/README.md
Documents configuration class and adds examples.
> Jwt auth documentation

- composer.lock
- config/bootstrap.php
- plugins/mixerapi/src/Plugin.php
> [MixerApi] - Make search plugin optional

- composer.json
- composer.lock
- plugins/collection-view/composer.json
> [CollectionView] - Set lowest adbario/php-dot-notation ^2.3

- composer.lock
- plugins/core/src/Model/TableScanner.php
- plugins/core/tests/TestCase/Model/TableScannerTest.php
- plugins/crud/tests/TestCase/Services/DeleteTest.php
- Removes some difficult to mock tests that are too reliant on cakephp internals
- Updates TableScanner to expect ConnectionInterface instead of the concrete Connection.
> Cleanup tests

- plugins/exception-render/src/MixerApiExceptionRenderer.php
- plugins/exception-render/tests/TestCase/ControllerTest.php
> MixerAPI/ExceptionRender - Remove exceptions property when debug is false

- .github/workflows/master.yml
- .github/workflows/pull-request.yml
- Adds php 8.2 to ci pipeline
- Sets master build to lowest supported version
> Adds php 8.2 to ci pipeline

- plugins/json-ld-view/src/JsonSerializer.php
- plugins/json-ld-view/tests/TestCase/JsonSerializerTest.php
> JsonLdView - Make collection code check for PaginatedResultSet

- plugins/collection-view/src/Serializer.php
- plugins/collection-view/tests/TestCase/SerializerTest.php
> CollectionView Show totalCount for total instead of page count

- config/.env.example
- plugins/collection-view/src/View/Helper/PagninatorHelper.php
- plugins/collection-view/src/View/JsonCollectionView.php
- plugins/collection-view/src/View/XmlCollectionView.php
- plugins/collection-view/tests/TestCase/ControllerTest.php
> CollectionView: Prevent URL escaping when listing pagination URLs
